name: Deploy Azure Network Infrastructure $(Build.BuildId)

trigger: none
#  branches:
#    include:
#    - main

variables:
  location: 'eastus'
  templateFile: '$(System.DefaultWorkingDirectory)\projects\az-networking\azure-network-infra.bicep'
  appName: 'webapp01'
  resourceGroupName: 'rg-network-01'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy Azure BiCEP Infrastructure
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\projects\az-networking'
              azureSubscription: 'Azure DevOps'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az --version
                az group create --name $(resourceGroupName) --location $(location)
                az deployment group what-if --resource-group $(resourceGroupName) \
                --template-file $(templateFile) \
                --parameters appName=$(appName)
