name: Deploy Azure Network Infrastructure $(Build.BuildId)


trigger: none
#  branches:
#    include:
#    - main

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'e2esa-azure-service-con'
  resourceGroupName: 'rg-dev'
  location: 'eastus'
  file: '$(System.DefaultWorkingDirectory)\projects\azure-bicep-host-website\src\network.bicep'
  environmentName: 'dev'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy Azure BiCEP Infrastructure
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'e2esa-azure-service-con'
              subscriptionId: 'bf793555-a4bc-42e3-a520-49d84c859f19'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-demo-01'
              location: 'Canada Central'
              templateLocation: 'URL of the file'
              csmFileLink: 'https://github.com/e2eSolutionArchitect/azure-bicep/blob/main/projects/azure-bicep-host-website/src/network.bicep'
              csmParametersFileLink: 'https://github.com/e2eSolutionArchitect/azure-bicep/blob/main/projects/azure-bicep-host-website/parameters/network.dev.bicepparam'
              deploymentMode: 'Validation'